In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#Load historical loan data - 20 past decisions

loan = pd.read_csv ('loan_applicants.csv')

print('Dataset shape: ', loan.shape)
print()
loan.head(8)

Dataset shape:  (20, 5)

  applicant_id  monthly_income  credit_score  employment_years  loan_approved
0     APP-1001          190891           364                 8              0
1     APP-1002          173646           807                14              0
2     APP-1003          545185           688                 6              1
3     APP-1004          148418           799                 0              0
4     APP-1005          458744           743                19              1
5     APP-1006           52208           756                 8              0
6     APP-1007          289874           404                10              0
7     APP-1008           82075           322                 0              0

In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load historical data - 20 past decisions

df = pd.read_csv('customer_churn.csv')

print('Dataset shape: ', df.shape)
print()
df.head(10)

Dataset shape:  (50, 5)

  customer_id  age  monthly_spend  num_complaints  churned
0    CUST-001   60           2324               0        1
1    CUST-002   37           4512               3        0
2    CUST-003   28          12566               1        0
3    CUST-004   54           1924               6        1
4    CUST-005   22            988               1        1
5    CUST-006   33           4311               8        1
6    CUST-007   58            934               8        1
7    CUST-008   32          12231               8        1
8    CUST-009   46           4111               7        1
9    CUST-010   57           5057               0        0

In [6]:
# Seperate features (X) from the label (y)
# Features = what we know about the churned
# Label = the outcome we're predicting

X = df[['age', 'monthly_spend', 'num_complaints']]

y = df['churned']

print('Features (X) - 3 columns, 20 rows:')
print(X.head(3))
print()
print('Label (y) - what we are predicting:')
print(y.values)
print(f'Approved: {y.sum()} | Rejected: {(y==0).sum()}')

Features (X) - 3 columns, 20 rows:
   age  monthly_spend  num_complaints
0   60           2324               0
1   37           4512               3
2   28          12566               1

Label (y) - what we are predicting:
[1 0 0 1 1 1 1 1 1 0 1 0 1 1 1 0 0 1 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0
 1 1 1 1 1 0 0 1 1 0 1 1 1]
Approved: 35 | Rejected: 15

In [ ]:
# Split : 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f'Training set: {len(X_train)} churned')
print(f'Test set: {len (X_test)} churned')
print()

# Train the ML Model -  it learns the rules from training data

model = DecisionTreeClassifier (random_state=42)
model.fit(X_train, y_train) #<-- this is where learning happens
print('Model trained. It has now seen: len(X_train), examples.')
print('It learned patterns-no rules were written by hand.')

Training set: 40 churned
Test set: 10 churned

Model trained. It has now seen: len(X_train), examples.
It learned patterns-no rules were written by hand.

In [ ]:
# Evaluate on test set - applicants the model has NEVER seen
print('Supervised Learning - loan prediction results:')
print('Test accuracy:', round(accuracy * 100), '%')
print()
print('Predictions vs Actual:')

# Turn y_test into a normal list so we can count through it with a new_number
actual_list = list(y_test)

# Go through each customer one at a time , using a simple counter(1)
for i in range (len(actual_list)):
    actual_value = actual_list[i]
    predicted_value = y_pred[i]

    if actual_value ==1:
        actual_text = 'approved'

    else:
        actual_text = 'rejected'

    if predicted_value == 1:
        predicted_value = 'approved'

    else:
        predicted_value = 'rejected'

    if actual_value == predicted_value:
        result = 'accurate'

    else:
        result = 'wrong'

    print('Customer', i + 1, '-> Actual:', actual_text, '| Predicted:', predicted_text, '| Model was', result)

In [18]:
import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import(
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

print('Libraries loaded successfully!')

#Load historical loan data - 20 past decisions

loan = pd.read_csv ('loan_applicants.csv')

print('Dataset shape: ', loan.shape)
print()
loan.head(8)

Libraries loaded successfully!
Dataset shape:  (20, 5)

  applicant_id  monthly_income  credit_score  employment_years  loan_approved
0     APP-1001          190891           364                 8              0
1     APP-1002          173646           807                14              0
2     APP-1003          545185           688                 6              1
3     APP-1004          148418           799                 0              0
4     APP-1005          458744           743                19              1
5     APP-1006           52208           756                 8              0
6     APP-1007          289874           404                10              0
7     APP-1008           82075           322                 0              0

In [10]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load historical transactions - 20 past decisions

df = pd.read_csv('opay_transactions.csv')

print('Dataset shape: ', df.shape)
print()
df.head(10)

Dataset shape:  (500, 6)

,amount,time_of_day,device_type,location_match,prev_fraud_flag,is_fraud
0,198805.0,6,2,0,0,0
1,263383.0,22,0,0,0,0
2,67840.0,3,1,1,0,0
3,161908.0,13,1,1,0,0
4,412514.0,10,0,1,0,0
5,221655.0,6,1,1,0,0
6,117720.0,20,3,1,0,0
7,248881.0,12,3,1,0,0
8,73538.0,0,1,1,0,0
9,358990.0,20,0,0,0,0

In [ ]:
# Seperate features (X) from the label (y)
# Features = what we know about the churned
# Label = the outcome we're predicting

X = df[['amount', 'time_of_day', 'device_type', 'location_match', 'prev_fraud_flag' ]]

y = df[['is_fraud']]

print('Features (X) - 3 columns, 20 rows:')
print(X.head(3))
print()
print('Label (y) - what we are predicting:')
print(y.values)
print(f'Approved: {y.sum()} | Rejected: {(y==0).sum()}')

Features (X) - 3 columns, 20 rows:
     amount  time_of_day  device_type  location_match  prev_fraud_flag
0  198805.0            6            2               0                0
1  263383.0           22            0               0                0
2   67840.0            3            1               1                0

Label (y) - what we are predicting:
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
Approved: is_fraud    21
dtype: int64 | Rejected: is_fraud    479
dtype: int64

In [25]:
# Split : Training (75%) , Testing (35%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)
print(f'Training set: {len(X_train)} is_fraud')
print(f'Test set: {len (X_test)} is_fraud')
print()

Training set: 375 is_fraud
Test set: 125 is_fraud

In [29]:
# Training the model to get the output
model = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

model.fit(X_train, y_train) #<-- this is where learning happens

print('Model training complete!')

Model training complete!

In [30]:
y_pred = model.predict(X_test)

print('Predictions made successfully!')
print('Number of Predictions:', len(y_pred))
print()

print('Actual Frauds:')
print(y_test.values)

print()
print('Model Predictions:')
print(y_pred)

Predictions made successfully!
Number of Predictions: 125

Actual Frauds:
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]

Model Predictions:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [27]:
cm = confusion_matrix(y_test, y_pred)

print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[119   1]
 [  4   1]]

In [31]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

print('True Negative (TN):', tn)
print('False Positive (FP):', fp)
print('False Negative (FN):', fn)
print('True Positive (TP):', tp)

True Negative (TN): 119
False Positive (FP): 1
False Negative (FN): 3
True Positive (TP): 2

In [ ]:
# To check accuracy 
# Accuracy = (TP + TN) / (TP + TN + FP + FN)

accuracy = accuracy_score(y_test, y_pred)

print('Accuracy:', round(accuracy * 100, 1), '%')

Accuracy: 96.8 %

In [ ]:
# To check precision
# Precision = TP / (TP + FP)

precision = precision_score(y_test, y_pred)

print('Precision:', round(precision * 100, 1), '%')

Precision: 66.7 %

In [34]:
# To check recall
# Recall = TP / (TP + FN)

recall = recall_score(y_test, y_pred)

print('Recall:', round(recall * 100, 1), '%')

Recall: 40.0 %

In [ ]:
# To check F1-SCORE
# F1-score combines Precision and recall

f1 = f1_score(y_test, y_pred)

print('F1-score:', round(f1 * 100, 1), '%')

F1-score: 50.0 %

In [36]:
print('===== MODEL EVALUATION =====')

print('Accuracy:', round(accuracy * 100, 1), '%')
print('Precision:', round(precision * 100, 1), '%')
print('Recall:', round(recall * 100, 1), '%')
print('F1-score:', round(f1 * 100, 1), '%')

print()
print('Confusion Matrix:')
print(cm)

===== MODEL EVALUATION =====
Accuracy: 96.8 %
Precision: 66.7 %
Recall: 40.0 %
F1-score: 50.0 %

Confusion Matrix:
[[119   1]
 [  4   1]]